set relativenumber

let mapleader = "<Space>"

" Show line numbers
set number

set visualbell
set scrolloff=10

" Remappings
nnoremap <Leader>e :vsc View.SolutionExplorer<CR>
nnoremap <Leader>sf :vsc Edit.GoToAll<CR>
nnoremap <Leader>sl :vsc Debug.Locals<CR>
nnoremap <Leader>sd :vsc View.ErrorList<CR>
nnoremap <Leader>sk :vsc Tools.CustomizeKeyboard<CR>
nnoremap <Leader>st :vsc TestExplorer.ShowTestExplorer<CR>
nnoremap <Leader>so :source ~\_vimrc<CR>:echo "_vimrc sourced..."<CR>
nnoremap <Leader>gs :vsc Team.Git.GoToGitChanges<CR>

nnoremap grd :vsc Edit.GoToDefinition<CR>
nnoremap grr :vsc Edit.GoToReference<CR>
nnoremap gri :vsc Edit.GoToImplementation<CR>

nnoremap gcc :vsc Edit.ToggleLineComment<CR>
vnoremap gc :vsc Edit.ToggleLineComment<CR>
