$env:PATH = "$env:PATH;$env:DOTFILES\shared\bin"
$env:PATH = "$env:PATH;C:\Users\NMiller\AppData\Local\Microsoft\WinGet\Links"
$env:PATH = "$env:PATH;C:\Program Files\ripgrep"
$env:PATH = "$env:PATH;C:\Tools"
$env:PATH = "$env:PATH;C:\Users\NMiller\AppData\Local\Programs\Python\Python313"
