$env:PATH = "$env:PATH;$env:DOTFILES\bin"
$env:PATH = "$env:PATH;C:\Users\NMiller\AppData\Local\Microsoft\WindowsApps"
$env:PATH = "$env:PATH;C:\Users\NMiller\AppData\Local\Microsoft\WinGet\Links"
$env:PATH = "$env:PATH;C:\Program Files\ripgrep"
$env:PATH = "$env:PATH;C:\Tools"
$env:PATH = "$env:PATH;C:\Users\NMiller\AppData\Local\Programs\Python\Python313"
$env:PATH = "$env:PATH;C:\Users\NMiller\AppData\Local\Programs\Python\Python313\Scripts"
$env:PATH = "$env:PATH;C:\Code\log-nolan\scripts\"
$env:PATH = "$env:PATH;C:\Program Files\Hugo"
$env:PATH = "$env:PATH;C:\Program Files\Go\bin"
$env:PATH = "$env:PATH;C:\Program Files\CMake\bin"
$env:PATH = "$env:PATH;C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.Emscripten.3.1.56.Sdk.win-x64\9.0.10\tools\bin"

# $env:PATH = "$env:PATH;C:\Users\NMiller\bin"
